name: Generate module 2
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    - name: Call standalone generator
      uses: guite/generator-action@master
      with:
        model_name: 'MultiHook.mostapp'
        module_name: 'Zikula/MultiHookModule'

    - name: Call standalone generator (verbose)
      uses: guite/generator-action@master
      with:
        model_name: 'MultiHook.mostapp'
        module_name: 'Zikula/MultiHookModule'
        verbose: true
