name: Generate module
# This workflow is triggered on pushes to the repository.
# TODO trigger after standalone generator is built instead
on:
  push:
    branches-ignore:
      - generator-update
#on: repository_dispatch

jobs:
  build:
#    env:
#      GENERATOR_BRANCH: 'generator-update'

    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from master branch
      uses: actions/checkout@v1
      with:
        ref: master

    - name: Create and switch to generator branch
      run: |
        ./.github/scripts/handle-branch.sh
      env:
        GENERATOR_BRANCH: 'generator-update'

    - name: Call standalone generator
      uses: guite/generator-action@master
      with:
        model_name: 'MultiHook.mostapp'
        module_name: 'Zikula/MultiHookModule'
        verbose: true

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m "Regenerated using latest generator :rocket:"

    # see https://github.com/ad-m/github-push-action
    #- name: Push changes to generator-update branch
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    branch: ${{ GENERATOR_BRANCH }}
    - name: Push changes to generator-update branch
      #run: git push --set-upstream origin ${{ GENERATOR_BRANCH }}
      run: |
        git push --set-upstream origin generator-update

    # see https://github.com/vsoch/pull-request-action
    - name: Create pull request
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #BRANCH_PREFIX: ${{ GENERATOR_BRANCH }}
        BRANCH_PREFIX: 'generator-update'
        PULL_REQUEST_BRANCH: 'master'
        PULL_REQUEST_TITLE: 'Generator update'
        PULL_REQUEST_BODY: 'Regenerated using latest generator :rocket:'
