name: Generate module
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    # see https://github.com/actions/setup-java
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
        architecture: x64

    - name: Call standalone generator
      run: ./.github/scripts/perform-generation.sh
      env:
        MODEL_NAME: 'MultiHook.mostapp'
        MODULE_NAME: 'Zikula/MultiHookModule'
