name: Test module
# This workflow is triggered on pushes to the repository and for pull requests.
on: [push, pull_request]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: zikula
          MYSQL_DATABASE: zikula
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    - name: Build and test
      uses: guite/zikula-action@master
      with:
        vendor-name: 'Zikula'
        module-name: 'MultiHook'
        module-version: '1.0.0'
        core-version: 'ZK3DEV'
        create-artifacts: true

    - name: Upload tar archive as artifact
      uses: actions/upload-artifact@master
      with:
        name: tar-archive
        path: './ZikulaMultiHookModule_v1.0.0.tar.gz'
    - name: Upload zip archive as artifact
      uses: actions/upload-artifact@master
      with:
        name: zip-archive
        path: './ZikulaMultiHookModule_v1.0.0.zip'
