name: Test module
# This workflow is triggered on pushes to the repository and for pull requests.
on: [push, pull_request]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    - name: Build and test
      uses: guite/zikula-action@master
      with:
        vendor-name: 'Zikula'
        module-name: 'MultiHook'
        module-version: '1.0.0'
        core-version: 'ZK30DEV'
        create-artifacts: true

    - uses: actions/upload-artifact@master
      with:
        name: tar-archive
        path: './ZikulaMultiHookModule_v1.0.0.tar.gz'
    - uses: actions/upload-artifact@master
      with:
        name: zip-archive
        path: './ZikulaMultiHookModule_v1.0.0.zip'
